version: "3.9"
services:
  web:
    image: "yykhomenko/hash-system:latest"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "cassandra:latest"
    hostname: cassandra
    restart: always

    healthcheck:
      test: [ "CMD", "cqlsh", "-e describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 10