#%RAML 1.0
title: Hash-system Msisdn REST API
version: v1
protocols: [ HTTP ]
baseUri: http://hash.system.com/api/{version}
securitySchemes:
  basic:
    type: Basic Authentication

/msisdn/{hash}:
  get:
    description: Get msisdn by hash.
    responses:
      200:
        body:
          application/json:
            type: |
            {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string",
                  "title": "msisdn by hash"
                }
              }
            }
            example: |
            {
              "value": "380672244089"
            }
      400:
        description: Hash is incorrect.
        body:
          application/json:
            type: |
            {
              "type": "object",
              "properties": {
                "errorId": {
                  "type": "integer",
                  "title": "error identifier"
                },
                "errorMsg": {
                  "type": "string",
                  "title": "error message"
                }
              }
            }
            example: |
            {
              "errorId": 5,
              "errorMsg": "Incorrect MSISDN format"
            }
      401:
        description: Login and password is not present or incorrect in request.
      403:
        description: Ip adress not allowed for this login.
      404:
        description: Msisdn by hash not exists.